// Generated by CoffeeScript 1.10.0
var arxiv, test_search;

arxiv = require('.');

test_search = {
  au: 'Xu_L',
  cat: 'cs*'
};

test_search = {
  title: 'RNN',
  author: 'William Chan'
};

arxiv.search(test_search, function(err, results) {
  return console.log(results.map(function(result) {
    return result.title + '\n - ' + result.authors.map(function(a) {
      return a.name;
    }).join(', ');
  }).join('\n\n'));
});
